name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.41.1'

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/krypton'

      - run: go tool task test

      - run: go tool task build

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: go tool task wrangler -- deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
